# Generated by Django 2.2.10 on 2020-08-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Главная')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(related_name='topices', through='articles.Principal', to='articles.Teams'),
        ),
    ]
